# Generated by Django 4.2.1 on 2023-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254),
        ),
    ]
